name: Octo Organization CI

on: 
  - push
  - workflow_dispatch

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  skip_me:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 
      - name: Pretend Job
        if: false
        continue-on-error: true
        run: echo "No" 

  build:
    needs: skip_me
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: |
          sleep 100
          exit 1

  step2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: |
          sleep 15
          echo World

  test2:
    uses: ./.github/workflows/test2.yaml
    with:
      workflowId: ${{ github.run_id }}
      attemptNumber: ${{ github.run_attempt }}
    permissions:
      id-token: write
      contents: read
      actions: write
    
      
      
