name: Subcall
on:
  workflow_call:
    inputs:
      workflowId:  
        description: "Run ID of the parent build pipeline"
        required: true
        type: string
      attemptNumber:  
        description: "Attempt number"  
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  wait_for_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKFLOW_ID: ${{ inputs.workflowId }}
      ATTEMPT_NUMBER: ${{ inputs.attemptNumber }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          #!/usr/bin/env bash
          while : ; do
            if [[ $WORKFLOW_ID != "" ]]; then
              url="/repos/${{ github.repository }}/actions/runs/$WORKFLOW_ID/attempts/$ATTEMPT_NUMBER"

              attempt=$(gh api \
                -H "Accept: application/vnd.github+json" \
                -H "X-Github-Api-Version: 2022-11-28" \
                "$url")

              echo "hi"
              status=$(echo "$attempt" | jq -er ".status")
              echo "hey"
              conclu=$(echo "$attempt" | jq -er ".conclusion")

              echo $status
              echo $conclu
              echo "---"
            fi
            
            sleep 15
          done
