name: Octo Organization CI

on: 
  - push
  - workflow_dispatch
  
jobs:
  skip_me:
    runs-on: ubuntu-latest
    if: false
    steps: 
      - name: Pretend Job
        run: echo "No" 

  build:
    needs: skip_me
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: |
          sleep 15
          echo Hello
  step2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: |
          sleep 15
          echo World
