name: Octo Organization CI

on: 
  - push
  - workflow_dispatch

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  step2:
    runs-on: windows-latest
    steps:
      - name: Job 2
        shell: pwsh
        run: |
          Write-Output (node --version)
          Write-Output (Get-Command node).Path
          ls 'C:\hostedtoolcache\windows\'
          ls 'C:\hostedtoolcache\windows\node'
          ls 'C:\hostedtoolcache\windows\node\22.14.0'
          ls 'C:\hostedtoolcache\windows\node\22.14.0\x64'
          Write-Output "QQ"
      - name: Prepare node
        uses: actions/setup-node@v4
        with:
          node-version: 22.*
          cache: npm
